Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,23 +15,30 @@ jobs:
 
     - name: Extract repository name
       id: extract_repo_name
-      run: echo "::set-output name=repo_name::${GITHUB_REPOSITORY##*/}"
+      run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
     - name: Send POST request to code analysis API
       id: send_request
       run: |
         owner=${{ github.repository_owner }}
-        repo=${{ steps.extract_repo_name.outputs.repo_name }}
+        repo=${{ env.REPO_NAME }}
         token=${{ secrets.MY_TOKEN }}
         echo "OWNER: $owner"
         echo "REPO: $repo"
-        response=$(curl -s -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=$owner&repo=$repo&token=$token")
+        response=$(curl -s -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerformStaticCodeAnalysis?owner=$owner&repo=$repo&token=$token")
+        
+        # Check if the curl request was successful
+        if [ $? -ne 0 ]; then
+          echo "Curl request failed"
+          exit 1
+        fi
+        
         echo "Response: $response"
-        echo "::set-output name=response::$response"
+        echo "response=$response" >> $GITHUB_ENV
 
     - name: Check API response
       run: |
-        if [ "${{ steps.send_request.outputs.response }}" != "true" ]; then
+        if [ "${{ env.response }}" != "true" ]; then
           echo "API Response is false. Failing the job."
           exit 1
         else
